# Generated by Django 5.0.1 on 2025-02-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_label_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail/'),
        ),
    ]
