# Generated by Django 5.0.1 on 2025-02-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_label_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='thumbnail/'),
        ),
    ]
